name: Deploy Flows

on:
#   push:
#     branches:
#       - "main"
  workflow_dispatch:

env:
    ENV_FILE: .ci/data-vent.yaml
    CONDA_ENV: data-vent
    CACHE_NUMBER: 0
    PREFECT_WORKSPACE: ooi-rca-prefect2

jobs:
  deploy:
    name: Deploy Prefect Flow
    runs-on: ubuntu-20.04
    defaults:
      run:
        shell: bash -l {0}
    env:
      OOI_USERNAME: ${{ secrets.OOI_USERNAME }}
      OOI_TOKEN: ${{ secrets.OOI_TOKEN }}
      AWS_KEY: ${{ secrets.AWS_KEY }}
      AWS_SECRET: ${{ secrets.AWS_SECRET }}
      PREFECT_KEY: ${{ secrets.PREFECT_KEY }}
      GH_PAT: ${{ secrets.GH_PAT }}
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Setup micromamba
        uses: mamba-org/provision-with-micromamba@v14
        with:
          environment-file: ${{ env.ENV_FILE }}
          environment-name: ${{ env.CONDA_ENV }}
          cache-env: false
      - name: Print conda env
        run: |
          conda info
          conda list
      - name: Install package
        run: |
          pip install .
      - name: Authenticate Prefect Cloud
        run: |
          prefect cloud login --key "$PREFECT_KEY" --workspace "${{ env.PREFECT_WORKSPACE }}"
      - name: Deploy Prefect Flows
        run: |
          pwd
          python ./deploy.py
   
      