name: Deploy Flows

on:
#   push:
#     branches:
#       - "main"
  workflow_dispatch:

env:
    ENV_FILE: .ci/metadata/data-vent-environment.yml #TODO make this yaml
    CONDA_ENV: data-vent
    CACHE_NUMBER: 0

jobs:
  register:
    name: Deploy Prefect Flow
    runs-on: ubuntu-20.04
    env:
     OOI_USERNAME: ${{ secrets.OOI_USERNAME }}
     OOI_TOKEN: ${{ secrets.OOI_TOKEN }}
     AWS_KEY: ${{ secrets.AWS_KEY }}
     AWS_SECRET: ${{ secrets.AWS_SECRET }}
     #GOOGLE_SERVICE_JSON: ${{ secrets.GOOGLE_SERVICE_JSON }}
     GH_PAT: ${{ secrets.GH_PAT }}
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_PAT }}
    #   - name: Login to DockerHub
    #     uses: docker/login-action@v1 
    #     with:
    #       username: ${{ secrets.DOCKER_USERNAME }}
    #       password: ${{ secrets.DOCKER_TOKEN }}
      - name: Setup micromamba
        uses: mamba-org/provision-with-micromamba@v14
        with:
          environment-file: ${{ env.ENV_FILE }}
          environment-name: ${{ env.CONDA_ENV }}
          cache-env: false
      - name: Print conda env
        run: |
          conda info
          conda list
      - name: Install package
        run: |
          pip install .
      - name: Deploy Prefect Flows
        run: |
          python ./deploy.py
   
      